config_dir = './data/config/';
config_name = {
               'RRT', ...
                   'RRTS', ...
                   'informedRRTSThresholdClose1', ...
                   'informedRRTSThresholdClose2', ...
                   'informedRRTSThresholdClose3', ...
                   'informedRRTSNeighborRange1', ...
                   'informedRRTSNeighborRange2', ...
                   'informedRRTSNeighborRange3', ...
                   'informedRRTScost1', ... only path
                   'informedRRTScost2', ...
                   'informedRRTScost3', ...
                   'informedRRT10times', ... only path
                   'RRTSFN', ...
                   'RRTSVS', ...
                   'RRTSVStimes', ...
               };
config_path = cell(length(config_name), 1);

for i = 1:length(config_name)
    config_path{i} = [config_dir, config_name{i}];
    t = rrt_func('config', config_path{i}, 'init', 'debug', 'get_repeat_times', 1);

    for j = 1:t
        rrt_func('run', [config_name{i},'-',num2str(j)])
    end

end
